### ISSUE TITLE
stdClass to model classes

### ISSUE THREAD

**Issue by timhovius** [nickpeirson/evohome-php#2]
Hello,

Do you think it's nessesary to convert stdClasses to model classes? See the example below:

```
public function setStatusAway(TemperatureControlSystem $temperatureControlSystem, \DateTime $until = null)
{
    $status = new Status();
    $status->setAway();
    $status->setTimeUntil($until);

    $response = $this->sendRequest(new TemperatureControlRequest($temperatureControlSystem, $status));
    return $response;
}
```

**Comment by nickpeirson** [comment]
Assuming you're talking about the response object, I think having an explicit model object is easier for someone using the library to work with, e.g. providing auto-completion for getters in an IDE. The alternative is to have doc blocks commenting the response, which isn't as nice.

There's a small performance overhead for the creation of a new object, but I don't think this is likely to be an issue for this library as it's unlikely to be used to make thousands of requests a second, particularly not when setting.

**Comment by timhovius** [comment]
Yes I am talking about the response object. I agree with you it's nicer; will create that :+1:
